image: Visual Studio 2019
configuration: Release - LLVM
platform: x64

install:
  - ps: bash.exe .ci/setup-windows.sh

build:
  project: rpcs3.sln
  parallel: true
  verbosity: normal

after_build:
  - ps: bash.exe .ci/deploy-windows.sh
