image: Visual Studio 2019
configuration: Release - LLVM
platform: x64

before_build:
  - sh: .ci/setup-windows.sh

build:
  project: rpcs3.sln
  parallel: true
  verbosity: normal

after_build:
  - sh: .ci/deploy-windows.sh
