image: Visual Studio 2019
configuration: Release - LLVM
platform: x64

install:
  - ps: .ci/setup-windows.sh
  - ps: sleep 60

build:
  project: rpcs3.sln
  parallel: true
  verbosity: normal

after_build:
  - ps: .ci/deploy-windows.sh
